# Optimized Game Configuration for Blast Off Billionaire
# Generated by simple_optimizer.py
# Target RTP: 95.00% | Expected RTP: 94.96%
# Hit Rate: 21.72% | Avg Win: 4.37x

self.multiplier_ranges = {
    "1.0-1.5": {"min": 1.0, "max": 1.5, "weight": 4607.21},  # 32.55% of wins
    "1.5-2.0": {"min": 1.5, "max": 2.0, "weight": 3455.41},  # 24.41% of wins
    "2.0-3.0": {"min": 2.0, "max": 3.0, "weight": 2303.61},  # 16.28% of wins
    "3.0-5.0": {"min": 3.0, "max": 5.0, "weight": 1727.70},  # 12.21% of wins
    "5.0-10.0": {"min": 5.0, "max": 10.0, "weight": 1151.80},  # 8.14% of wins
    "10-20": {"min": 10.0, "max": 20.0, "weight": 575.90},  # 4.07% of wins
    "20-40": {"min": 20.0, "max": 40.0, "weight": 230.36},  # 1.63% of wins
    "40-80": {"min": 40.0, "max": 80.0, "weight": 69.11},  # 0.49% of wins
    "80-160": {"min": 80.0, "max": 160.0, "weight": 23.04},  # 0.16% of wins
    "160-320": {"min": 160.0, "max": 320.0, "weight": 5.76},  # 0.04% of wins
    "320-800": {"min": 320.0, "max": 800.0, "weight": 2.30},  # 0.02% of wins
    "800-2000": {"min": 800.0, "max": 2000.0, "weight": 1.15},  # 0.01% of wins
    "2000-5000": {"min": 2000.0, "max": 5000.0, "weight": 0.58},  # 0.00% of wins
    # Loss case (no win)
    "0": {"min": 0.0, "max": 0.0, "weight": 51007.09},  # 78.28% of spins
}

# Update bet modes with optimized distribution
for bet_mode in self.bet_modes:
    for dist in bet_mode.distributions:
        if dist.criteria == "0":
            dist.quota = 0.7828  # Loss rate
        elif dist.criteria == "basegame":
            dist.quota = 0.2167  # Win rate - wincap adjustment
